DjangoTraining/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404
from polls import views


handler404 = 'polls.views.custom_404'

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),

]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('thanks/', views.thanks, name='thanks'),
    path('contactus/', views.ContactView.as_view(), name='contactus')
]

polls/models.py
from django.db import models


class Question(models.Model):

    question_txt = models.CharField(max_length=100)
    pub_date = models.DateTimeField('published date')

    def __str__(self):

        return (f'Question description : {self.question_txt}\n'
                f'Published date: {self.pub_date}\n')


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_txt = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):

        return (f'Choice Description : {self.choice_txt}\n'
                f'Votes Received : {self.votes}\n'
                f'Question to which choice is linked: {self.question}\n')

users/models.py
# from django.db import models
# from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
# from .managers import CustomUserManager
# # Create your models here.
#
#
# class CustomUser(AbstractBaseUser, PermissionsMixin):
#
#     email = models.EmailField(unique=True)
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     is_active = models.BooleanField(default=True)
#     is_staff = models.BooleanField(default=False)
#
#     objects = CustomUserManager()
#
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['first_name', 'last_name']
#
#     def __str__(self):
#
#         return self.email
#
#

polls/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Question, Choice
from django.urls import reverse
from .forms import ContactForm
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


def custom_404(request, exception):

    return render(request, 'polls/404.html', status=404)


def home(request):

    if request.user.is_authenticated:

        return HttpResponseRedirect(reverse('polls:index'))

    return render(request, 'polls/home.html')


class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):

        return Question.objects.order_by("-pub_date")[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):

    model = Question
    template_name = 'polls/detail.html'


class ResultsView(LoginRequiredMixin, generic.DetailView):

    model = Question
    template_name = 'polls/results.html'


class ContactView(LoginRequiredMixin, View):

    template_name = 'polls/contact.html'
    form_class = ContactForm

    def get(self, request, *args, **kwargs):

        form = self.form_class()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)
        if form.is_valid():

            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["sender"]
            cc_myself = form.cleaned_data["cc_myself"]

            recipients = []
            if cc_myself:
                recipients.append(sender)

            return HttpResponseRedirect(reverse('polls:thanks'))

        return render(request, self.template_name, {'form': form})


@login_required()
def thanks(request):

    return HttpResponse('Your Contact Form Submitted Successfully')


@login_required()
def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {
                'question': question,
                'error_message': "You didn't select a choice.",
            },
        )

    else:

        selected_choice.votes = F('votes') + 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def login_view(request):

    return render(request, 'registration/login.html')

users/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/polls/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form action=" {% url 'polls:contactus' %} " method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Submit">

  </form>
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'polls:vote' question.id %} " method="post">
    {% csrf_token %}
   <fieldset>
       <legend>
           <h1>
               {{ question.question_txt }}
           </h1>
       </legend>

       {% if error_message %}
           <p>
               <strong>
                   {{ error_message }}
               </strong>
           </p>
       {% endif %}

       {% for choice in question.choice_set.all %}
           <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
           <label for="choice{{forloop.counter}}">
               {{ choice.choice_txt }}
           </label><br>
       {% endfor %}
   </fieldset>
    <input type="submit" value="Vote">
</form>

</body>
</html>

polls/templates/polls/home.html
<!-- templates/home.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Welcome to the Polls App</h1>
    <p>To use the app you need to first login</p>


 <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <button type="submit">Log In</button>
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.question_txt }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
 <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Log out</button>
</form>

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    {{ question.question_txt }}
</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>